FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install

COPY . .

# Generate Prisma Client
RUN npx --no-install prisma generate --schema=../database/schema.prisma

RUN npm run build

EXPOSE 5000

CMD ["npm", "start"]
